services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  api:
    build: .
    container_name: fastapi_app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/tasks_db
    ports:
      - "8000:8000"

volumes:
  postgres_data: